/**
 * bench-aggregator.ts — Phase 4b-8 vendor matrix aggregator + markdown report.
 *
 * Reads multiple BenchmarkResult JSON files (one per vendor / environment) and
 * produces:
 *   - `aggregate(results)`: per-vendor warm p99 / cold latency / metric counts
 *   - `formatMarkdownTable(rows)`: GitHub-flavored markdown table
 *
 * Used by `scripts/generate-bench-report.mjs` to publish L6 vendor portability
 * tables in README.
 */

import { readFileSync } from "node:fs";

import type { BenchmarkResult } from "./benchmark.js";
import { warmP99 } from "./bench-runner.js";

export interface VendorRow {
  /** Display label, e.g. "AMD Radeon RX 9070 XT (RDNA4)" */
  label: string;
  /** Source bench.json path (or any unique identifier). */
  source: string;
  /** Warm p99 latency in ms, or null if no warm metrics (evicted run). */
  warmP99Ms: number | null;
  /** Cold latency in ms (first cold metric), or null if absent. */
  coldMs: number | null;
  /** Number of warm samples (sample size for p99 stability). */
  warmSamples: number;
  /** Whether the run completed in "warm" state (false = evicted). */
  ranWarm: boolean;
  /** Notes propagated from the cold metric (e.g. "evicted (state=evicted)..."). */
  notes?: string;
}

/**
 * Convert a single BenchmarkResult into a VendorRow.
 */
export function aggregateOne(result: BenchmarkResult, source: string): VendorRow {
  const cold = result.metrics.find((m) => m.mode === "cold");
  const warm = result.metrics.filter((m) => m.mode === "warm");
  const profile = result.capabilityProfile;
  const label = profile
    ? `${profile.gpuVendor} ${profile.gpuDevice} (${profile.gpuArch})`.trim()
    : `Unknown (${source})`;
  const ranWarm = warm.length > 0;
  return {
    label,
    source,
    warmP99Ms: ranWarm ? warmP99(result) : null,
    coldMs: cold ? cold.latencyMs : null,
    warmSamples: warm.length,
    ranWarm,
    notes: cold?.notes,
  };
}

/**
 * Aggregate multiple BenchmarkResult into a sorted vendor matrix.
 * Sorted by warmP99 ascending (faster vendors first), evicted runs last.
 */
export function aggregate(
  inputs: Array<{ result: BenchmarkResult; source: string }>,
): VendorRow[] {
  const rows = inputs.map(({ result, source }) => aggregateOne(result, source));
  rows.sort((a, b) => {
    if (!a.ranWarm && b.ranWarm) return 1;
    if (a.ranWarm && !b.ranWarm) return -1;
    if (a.warmP99Ms === null && b.warmP99Ms === null) return 0;
    if (a.warmP99Ms === null) return 1;
    if (b.warmP99Ms === null) return -1;
    return a.warmP99Ms - b.warmP99Ms;
  });
  return rows;
}

/**
 * Read a bench.json file and return the parsed BenchmarkResult.
 * Throws on file-not-found / parse error — caller decides how to handle.
 */
export function readBenchFile(path: string): BenchmarkResult {
  const raw = readFileSync(path, "utf8");
  return JSON.parse(raw) as BenchmarkResult;
}

/**
 * Generate a GitHub-flavored markdown table from VendorRows.
 *
 * Layout:
 * | Vendor                                | warm p99 | cold | samples | notes |
 * |---------------------------------------|---------:|-----:|--------:|-------|
 * | AMD Radeon RX 9070 XT (RDNA4)         |  18.5 ms | 240 ms | 20 | — |
 * | (evicted) Intel Iris Xe (Xe)          |        — |   — |  0 | artifact missing |
 */
export function formatMarkdownTable(rows: VendorRow[]): string {
  if (rows.length === 0) return "_(no benchmark inputs)_\n";
  const lines: string[] = [];
  lines.push("| Vendor | warm p99 | cold | samples | notes |");
  lines.push("|---|---:|---:|---:|---|");
  for (const r of rows) {
    const w = r.warmP99Ms === null ? "—" : `${r.warmP99Ms.toFixed(1)} ms`;
    const c = r.coldMs === null ? "—" : `${r.coldMs.toFixed(1)} ms`;
    const note = r.notes ? r.notes.replace(/\|/g, "\\|") : (r.ranWarm ? "—" : "_evicted_");
    lines.push(`| ${r.label.replace(/\|/g, "\\|")} | ${w} | ${c} | ${r.warmSamples} | ${note} |`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Generate the full BENCH.md content (table + L1 target callout).
 */
export function formatBenchMarkdown(rows: VendorRow[]): string {
  const banner = [
    "# Visual GPU Phase 4 — Vendor Matrix",
    "",
    "Generated by `scripts/generate-bench-report.mjs` from bench.json files.",
    "",
    "**ADR-005 L1 target**: warm p99 ≤ 30ms (RX 9070 XT dogfood baseline).",
    "**ADR-005 L4 target**: GPU steady-state ≤ 25% (out of scope here, measured separately).",
    "**ADR-005 L6 target**: vendor portability — every vendor cell should show a real warm p99,",
    "no `_evicted_` rows for supported vendors.",
    "",
  ].join("\n");
  return banner + formatMarkdownTable(rows);
}
