// Native* type aliases for the napi-rs addon.
// This is the single source of truth — import Native* types from here, not from index.d.ts.
// index.d.ts is auto-generated by napi-rs and does not preserve these aliases.

export interface NativeBoundingRect {
  x: number
  y: number
  width: number
  height: number
}

export interface NativeUiElement {
  name: string
  controlType: string
  automationId: string
  className?: string
  isEnabled: boolean
  boundingRect?: NativeBoundingRect | null
  patterns: Array<string>
  depth: number
  value?: string
}

export interface NativeUiElementsResult {
  windowTitle: string
  windowClassName?: string | null
  windowRect?: NativeBoundingRect | null
  elementCount: number
  elements: Array<NativeUiElement>
}

export interface NativeScrollResult {
  ok: boolean
  scrolled: boolean
  error?: string | null
}

export interface NativeScrollAncestor {
  name: string
  automationId: string
  controlType: string
  verticalPercent: number
  horizontalPercent: number
  verticallyScrollable: boolean
  horizontallyScrollable: boolean
}

export interface NativeUiaFocusInfo {
  name: string
  controlType: string
  automationId?: string
  value?: string
}

// ─── L3 perception view (ADR-008 D2-B-1) ─────────────────────────────────────
// Returned by `viewGetFocused()` (root-level napi export). Mirrors the
// engine-perception `latest_focus` view's `UiElementRef`, with
// `controlType` pre-stringified via `crate::uia::control_type_name` so
// the shape matches the existing `NativeUiaFocusInfo` consumer in
// `desktop-state.ts` (Codex review v3 P1-3 bit-equal contract).

export interface NativeFocusedElement {
  name: string
  automationId: string | null
  controlType: string
  windowTitle: string
}

export interface NativeViewFocusedPipelineStatus {
  initialized: boolean
  /** `true` when the slot's pipeline has had a failed shutdown
   * (Codex review v9 P2-17). Callers should fall back to UIA. */
  poisoned: boolean
  /** Cumulative `Cmd::PushFocus` count. **Focus-only since S2 D2-C**
   * (Codex PR #108 round 1 P2-B): dirty-rect traffic uses a separate
   * Rust-side counter (`PerceptionWorker::processed_dirty_rect_count`).
   * Do NOT use this as overall pipeline activity gauge — it explicitly
   * excludes dirty-rect events to keep focus-pipeline telemetry
   * isolated. */
  processedCount: bigint
}

// ─── L4 envelope helper (S3 D2-E0 P1, ADR-010) ──────────────────────────────
// Returned by `viewGetFocusedWithWallclock()`. Used by the L4 envelope
// wrapper (`src/tools/_envelope.ts::makeEnvelopeAware`) to build
// `as_of.wallclock_ms` from L1 event time (NOT server-side `Date.now()`,
// ADR-010 §5 + §4.1 Provenance, PR #110 Round 1 P1-4 反映).

export interface NativeFocusedElementWithWallclock {
  /** Focused element shape; **omitted** by napi-rs (NOT set to `null`)
   * when no live focus / pipeline poisoned (PR #112 Round 1 P2-B,
   * user review): napi-rs serialises `Option::None` for nested struct
   * fields by **omitting the key**, not setting it to `null`. The TS
   * type is `optional + null` (rather than the previous `required +
   * null`) so consumers must check both `=== null` and `=== undefined`,
   * or use `result.focused != null` (covers both omission and a
   * hypothetical future explicit null). Same root cause as PR #108
   * `NativeDirtyRectsResult.latest` and memory
   * `feedback_napi_default_export.md`. */
  focused?: NativeFocusedElement | null
  /** Wallclock_ms of the latest live focus event; **omitted** by napi-rs
   * when no event observed yet (same `Option::None` omission semantic
   * as `focused`). Caller uses `Date.now()` + `confidence: degraded`
   * fallback. */
  latestEventWallclockMs?: bigint | null
  /** True when pipeline slot is poisoned. Caller falls back to UIA path. */
  viewPoisoned: boolean
}

// ─── L3 perception dirty_rects_aggregate view (S2 D2-C) ──────────────────────
// Returned by `viewGetDirtyRects(monitorIndex)`. Count-only contract spike
// per `docs/adr-008-d2-c-plan.md` §2.3 / §3.7 — no rect geometry, just a
// per-`(monitor, frame)` count and the latest frame for the queried monitor.

export interface NativeDirtyRectFrame {
  frameIndex: bigint
  count: bigint
}

export interface NativeDirtyRectsResult {
  /** The `monitor_index` the caller asked for, echoed back so the TS
   * layer can confirm round-trip integrity (CLAUDE.md §3.2 PR #102 教訓). */
  monitorIndex: number
  liveFrameCount: number
  /** Most recent `(frame_index, count)` for this monitor, if any.
   * **Optional** because napi-rs serialises `Option::None` for nested
   * struct fields by **omitting** the key (not setting it to `null`).
   * User review on PR #108 (2026-05-01) pinned the runtime behaviour.
   * Use optional chaining (`result.latest?.frameIndex`) or
   * `result.latest != null` (covers both `undefined` from omission
   * and a hypothetical future `null`). */
  latest?: NativeDirtyRectFrame
}

export interface NativeFocusAndPointResult {
  focused?: NativeUiaFocusInfo | null
  atPoint?: NativeUiaFocusInfo | null
}

export interface NativeActionResult {
  ok: boolean
  element?: string | null
  error?: string | null
  code?: string | null
}

export interface NativeElementBounds {
  name: string
  controlType: string
  automationId: string
  boundingRect?: NativeBoundingRect | null
  value?: string | null
}

export interface NativePreprocessOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  /** Upscale factor: 1, 2, 3, or 4. Values above 4 are rejected by the Rust layer. */
  scale: number
  /** When true, apply Sauvola adaptive binarization after contrast stretch (output: 0/255 only). */
  adaptive?: boolean
}

export interface NativeImageProcessingResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

export interface NativeSomLabel {
  id: number
  x: number
  y: number
  width: number
  height: number
}

export interface NativeDrawSomLabelsOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  labels: Array<NativeSomLabel>
}

export interface NativeDrawSomLabelsResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

// ─── SSIM residual (ADR-019 Stage 4) ─────────────────────────────────────────
//
// Native shapes for `compute_ssim_residual` (Wang et al. 2004 implementation,
// see `src/ssim.rs`). Used by the Stage 4 `local_repaint` orchestrator
// (`src/engine/local-repaint.ts`) under the `ssim_residual` source label
// in `VisualMotionObservation`. Bit-equal mirror of the napi-rs Rust shapes;
// keep in sync with the hand-maintained re-export in `index.d.ts` and the
// runtime export in `index.js`.

/** Optional sub-region selector (pre / post coordinates). Omitted /
 *  `null` selects the whole frame. */
export interface NativeSsimRegion {
  x: number
  y: number
  width: number
  height: number
}

/** Centroid of above-threshold sliding windows. Coordinates are in absolute
 *  frame pixels (NOT region-relative); callers that supply a sub-region
 *  receive the centroid in the same frame coordinate space. **Omitted**
 *  (NOT `null`) by napi-rs when `fractionChanged === 0` — same
 *  `Option::None` omission semantic as `NativeDirtyRectsResult.latest`. */
export interface NativeSsimCentroid {
  x: number
  y: number
}

/** Aggregated SSIM residual over the requested region. `fractionChanged`
 *  is the fraction of 8×8 sliding windows (stride 4) whose `1 - SSIM`
 *  exceeded the per-window residual threshold (0.05 default in
 *  `src/ssim.rs`). `meanSsim` is the Wang "perceptually identical" cutoff
 *  used by Stage 4 to discriminate `no_change` (≥ 0.99) from
 *  `indeterminate` (< 0.99) — also exposed via
 *  `VisualMotionObservation.residual.meanSsim` per Stage 4 sub-plan §4 P15
 *  decision lock default (a). */
export interface NativeSsimResidualResult {
  fractionChanged: number
  /** Omitted (not `null`) when `fractionChanged === 0`. Use `result.centroid != null`
   *  to handle both `undefined` (napi-rs omission) and a hypothetical
   *  future explicit `null`. */
  centroid?: NativeSsimCentroid
  meanSsim: number
}

// ── Win32 hot-path bindings (ADR-007 P1) ─────────────────────────────────────

/** Rust `RECT` mirror — left/top/right/bottom in screen pixels. The TS wrapper
 *  in `src/engine/win32.ts` converts to `{ x, y, width, height }` for callers. */
export interface NativeWin32Rect {
  left: number
  top: number
  right: number
  bottom: number
}

/** Combined return for `GetWindowThreadProcessId`. The Win32 API's out-pointer
 *  + return value are folded into one struct so the TS wrapper just reads
 *  `.threadId` / `.processId`. */
export interface NativeThreadProcessId {
  threadId: number
  processId: number
}

// ── Win32 GDI / monitor / DPI (ADR-007 P2) ───────────────────────────────────

/** Result of `win32PrintWindowToBuffer`: RGBA top-down pixels (length = w*h*4). */
export interface NativePrintWindowResult {
  data: Buffer
  width: number
  height: number
}

/** One monitor as returned by `win32EnumMonitors`. The TS wrapper rebuilds
 *  the nested `{ bounds, workArea }` shape that callers (`MonitorInfo`)
 *  expect — this flat record matches the napi marshal layout. */
export interface NativeMonitorInfo {
  handle: bigint
  primary: boolean
  boundsLeft: number
  boundsTop: number
  boundsRight: number
  boundsBottom: number
  workLeft: number
  workTop: number
  workRight: number
  workBottom: number
  dpi: number
}

// ── Win32 process / input (ADR-007 P3) ───────────────────────────────────────

/** Outcome of `win32ForceSetForegroundWindow`. The TS wrapper repacks
 *  these into snake_case (`fg_before` / `fg_after`) for legacy public API
 *  compatibility (Tool Surface 不変原則 P7). */
export interface NativeForceFocusResult {
  ok: boolean
  attached: boolean
  fgBefore: bigint
  fgAfter: bigint
}

// ── ADR-013 Option E (`foreground_flash` channel、Phase 1c-1f) ──────────────

/** Caller-supplied options for `win32ForegroundFlashInject`.
 *  All fields optional with defaults documented in
 *  `src/win32/foreground_flash.rs` constants. */
export interface NativeForegroundFlashOptions {
  /** Focus-ready 判定 polling 上限 (default 30ms)。 */
  maxFocusWaitMs?: number
  /** Foreground 復帰 retry 回数 (default 2)。 */
  foregroundRestoreRetries?: number
  /** LowLevel keyboard hook で flash 中の keystroke を block する (default false)。
   *  env `DESKTOP_TOUCH_FOREGROUND_FLASH_BLOCK_KEYBOARD=1` で global ON。 */
  blockKeyboardDuringFlash?: boolean
  /** WT paste warning ContentDialog scan を有効化 (default true)。
   *  env `DESKTOP_TOUCH_FOREGROUND_FLASH_DISABLE_DIALOG_SCAN=1` で OFF。 */
  scanPasteWarningDialog?: boolean
  /** Paste 完了後に SendInput(VK_RETURN) を別送信 (default false)。 */
  pressEnter?: boolean
}

/** One entry in `ForegroundFlashResult.clipboardSkippedFormats`. */
export interface NativeForegroundFlashSkippedFormat {
  formatId: number
  /** Skip 理由: `"non_hglobal"` / `"deferred_render"` / `"get_data_failed"`。 */
  reason: string
}

/** Successful return of `win32ForegroundFlashInject`. Failure paths throw
 *  `Error` whose `message` carries the typed reason string (snake_case):
 *  - `input_contains_newline`
 *  - `input_exceeds_paste_warning_threshold`
 *  - `foreground_steal_denied`
 *  - `focus_wait_timeout`
 *  - `clipboard_lock_contention`
 *  - `foreground_restore_failed`
 *  - `wt_paste_warning_intercepted`
 *  - `send_input_failed`
 */
export interface NativeForegroundFlashResult {
  /** Flash 全体所要時間 (ms、ladder + paste + restore + dialog scan 含む)。 */
  flashDurationMs: number
  /** `"AttachThreadInput"` (段 1) / `"alt_unlock"` (段 2) /
   *  `"already_foreground"` (skip)。 */
  foregroundStealMethod: string
  /** Foreground 復帰確認済 (`GetForegroundWindow == originalForegroundHwnd`)。 */
  foregroundRestored: boolean
  /** Foreground 復帰の retry 回数 (0 = 1 回目で成功; 1 attempt 内で 段 1 →
   *  段 2 fallback も "0" 扱い、ladder 段 1/2 区別は `foregroundRestoreMethod`
   *  側で記録、Opus Round 1 P1-2 反映)。 */
  foregroundRestoreRetriesUsed: number
  /** Foreground 復帰時に成功した ladder 段。
   *  `"AttachThreadInput"` / `"alt_unlock"` / `"none"` (already_foreground)。
   *  retry observability を steal 側と対称化 (Opus Round 1 P1-2)。 */
  foregroundRestoreMethod: string
  /** Clipboard 復元実施 (false = race detected / restore 中 fail で skip)。 */
  clipboardRestored: boolean
  /** Clipboard save 時 skip された format (非 HGLOBAL / 遅延 rendering)。 */
  clipboardSkippedFormats: Array<NativeForegroundFlashSkippedFormat>
  /** Paste warning dialog が検出されたか (検出時は別途 fail → throw)。 */
  pasteWarningDetected: boolean
}

/** One Toolhelp32 row. The TS wrapper builds a Map<number, number>. */
export interface NativeProcessParentEntry {
  pid: number
  parentPid: number
}

/** Process identity result. Partial success is allowed: a missing
 *  process_name leaves it as "" and a missing creation time leaves
 *  process_start_time_ms = 0. */
export interface NativeProcessIdentity {
  pid: number
  processName: string
  processStartTimeMs: number
}

/** Scrollbar position snapshot. `pageRatio` (0..1) is precomputed. */
export interface NativeScrollInfo {
  nMin: number
  nMax: number
  nPage: number
  nPos: number
  pageRatio: number
}

// ── ADR-017: read-only Terminal Services session row ────────────────────────
//
// Returned by `wtsEnumerateSessions()`. One entry per session known to the
// local Win32 `WTSEnumerateSessionsW` API. Used by the TS classifier in
// `desktop-state.ts` to derive `sessionLabel` / `sessionState` for the
// optional `sessionContext` block on `desktop_state` responses.

export interface NativeWtsSessionInfo {
  /** Terminal Services session id (mirrors `WTS_SESSION_INFOW.SessionId`). */
  sessionId: number
  /** Win-station name (e.g. `"Console"`, `"RDP-Tcp#0"`, `"Services"`). May
   *  be `""` when the WTS layer hands us a null pointer (rare). */
  winStation: string
  /** Raw `WTS_CONNECTSTATE_CLASS` numeric. 0=Active, 1=Connected,
   *  2=ConnectQuery, 3=Shadow, 4=Disconnected, 5=Idle, 6=Listen,
   *  7=Reset, 8=Down, 9=Init. */
  state: number
  /** Pre-stringified state label (`"active"` / `"connected"` /
   *  `"disconnected"` / `"listen"` / etc.). Unknown values surface as
   *  `"state_<numeric>"` so future Windows releases can be diagnosed. */
  stateLabel: string
}

// ── Desktop Duplication (Phase 3) ────────────────────────────────────────────

export interface NativeDirtyRect {
  x: number
  y: number
  width: number
  height: number
}

export interface NativeOutputBounds {
  x: number
  y: number
  width: number
  height: number
}

/**
 * ADR-019 Stage 5 — typed declaration for the `DirtyRectSubscription` napi
 * class (`src/duplication/mod.rs`). The class shipped with PR #102 (ADR-007
 * P5c-2) and was originally reachable only through an untyped escape hatch
 * (`addon["DirtyRectSubscription"]` in `src/engine/vision-gpu/dirty-rect-source.ts`,
 * removed in ADR-020 SR-4 PR-SR4-3). Both consumers (Stage 5 via
 * `src/engine/any-change.ts`, vision-gpu via `dirty-rect-source.ts`) now go
 * through the shared `DirtyRectBroker` (`src/engine/dxgi-broker.ts`), which
 * is the single typed caller of `nativeDuplication.DirtyRectSubscription`.
 *
 * `outputBounds` is the per-output desktop rect (now populated from
 * `DXGI_OUTPUT_DESC.DesktopCoordinates` after PR #322, so dirty rects are
 * translated to desktop screen coords for ALL monitors, not just primary).
 */
export interface NativeDirtyRectSubscription {
  readonly isDisposed: boolean
  readonly outputBounds: NativeOutputBounds
  next(timeoutMs: number): Promise<NativeDirtyRect[]>
  dispose(): void
}

/**
 * ADR-020 SR-4 PR-SR4-1 — re-export of the broker handle interface so
 * downstream consumers (Stage 5 in PR-SR4-2, vision-gpu in PR-SR4-3) can
 * reference the typed handle from a single SSOT (`native-types.ts`).
 *
 * The actual interface definition lives in `src/engine/dxgi-broker.ts`
 * (where the broker class also lives). This file re-exports the type so
 * sub-plan §5.2's "BrokerSubscription re-exported interface" SSOT row
 * is satisfied without duplicating the declaration.
 *
 * Per Round 2 P1-3 lock: this interface has no `subscribe()` method —
 * fan-out is exclusively a `DirtyRectBroker.subscribe()` upper-level API
 * responsibility.
 */
export type { BrokerSubscription } from "./dxgi-broker.js"

// ── Visual GPU Phase 4 (ADR-005) ─────────────────────────────────────────────

/** Rust src/vision_backend/types.rs::Rect */
export interface NativeVisionRect {
  x: number
  y: number
  width: number
  height: number
}

/** Rust src/vision_backend/types.rs::RoiInput */
export interface NativeRoiInput {
  trackId: string
  rect: NativeVisionRect
  classHint?: string | null
}

/** Rust src/vision_backend/types.rs::RecognizeRequest */
export interface NativeRecognizeRequest {
  targetKey: string
  /** Session key from `init_session_blocking`. Empty string → legacy dummy path. */
  sessionKey: string
  rois: NativeRoiInput[]
  frameWidth: number
  frameHeight: number
  /** Captured frame RGBA bytes, length = frameWidth * frameHeight * 4.
   *  Empty Buffer → legacy dummy path (no preprocess, stub candidates). */
  frameBuffer: Buffer
  nowMs: number
}

/** Rust src/vision_backend/types.rs::RawCandidate */
export interface NativeRawCandidate {
  trackId: string
  rect: NativeVisionRect
  /** Empty string when class is "icon" or detection found a non-text element. */
  label: string
  /** "text"|"icon"|"mixed"|"button"|"checkbox"|"radio"|"dropdown"|"slider"|"tab"|"label"|"image"|"title"|"other" */
  class: string
  confidence: number
  provisional: boolean
}

/**
 * Rust src/vision_backend/capability.rs::CapabilityProfile
 *
 * Sample for the dogfood machine (RX 9070 XT, Win11 24H2):
 *   { os: "windows", osBuild: 26100, gpuVendor: "AMD", gpuArch: "RDNA4", winml: true, directml: true, ... }
 */
export interface NativeCapabilityProfile {
  os: string
  osBuild: number
  gpuVendor: string
  gpuDevice: string
  gpuArch: string
  gpuVramMb: number
  winml: boolean
  directml: boolean
  rocm: boolean
  cuda: boolean
  tensorrt: boolean
  cpuIsa: string[]
  backendBuilt: boolean
  epsBuilt: string[]
}

// ── Phase 4b-1: EP cascade session init ──────────────────────────────────────

/**
 * Rust src/vision_backend/types.rs::NativeSessionInit
 *
 * Input to `visionInitSession`. `profile` should be obtained from
 * `detectCapability()` so the cascade can select the optimal EP.
 */
export interface NativeSessionInit {
  /** Absolute path to the .onnx file to load. */
  modelPath: string
  /** CapabilityProfile produced by detectCapability(). */
  profile: NativeCapabilityProfile
  /**
   * Optional stable session key for later pool lookup (e.g. "ui_detector:dml-fp16").
   * Pass an empty string for ad-hoc sessions.
   */
  sessionKey: string
}

/**
 * Rust src/vision_backend/types.rs::NativeSessionResult
 *
 * Returned by `visionInitSession`. The Promise **never rejects** — errors are
 * reported via `ok === false` to maintain L5 process isolation.
 */
export interface NativeSessionResult {
  ok: boolean
  /**
   * Set when `ok === true`. Format: "WinML" | "DirectML(0)" | "ROCm(0)" |
   * "CUDA(0)" | "CPU" | "Fallback(reason)"
   */
  selectedEp: string
  /** Set when `ok === false`. Concatenated cascade attempt errors. */
  error?: string | null
  /** Echoed `sessionKey` — use as lookup key for subsequent recognize_rois calls (4b-4+). */
  sessionKey: string
}

// ── ADR-007 P5a: L1 capture ring buffer ──────────────────────────────────────

/** napi 公開する EventEnvelope の TS 側表現。Rust 内部の InternalEvent は
 *  payload を Vec<u8> で所有するが、JS 側では Buffer (fresh allocation) として渡る。 */
export interface NativeEventEnvelope {
  envelopeVersion: number
  eventId: bigint
  wallclockMs: bigint
  subOrdinal: number
  timestampSource: number
  kind: number
  payloadBytes: Buffer
  sessionId?: string | null
  toolCallId?: string | null
}

/** L1 ring buffer のヘルスチェック結果。bench / server_status 用。 */
export interface NativeCaptureStats {
  uptimeMs: bigint
  pushCount: bigint
  dropCount: bigint
  currentBuffered: number
  panicCount: bigint
  eventIdHighWater: bigint
}

/**
 * Lease 4-tuple summary attached to `l1PushToolCallStarted` (ADR-010 P1 S4
 * sub-plan `docs/adr-010-p1-s4-plan.md` §2.3). Mirrors the runtime
 * `EntityLease` (`src/engine/world-graph/types.ts`) minus `expiresAtMs`
 * (commit-time validation has already consumed the TTL) and with
 * `evidenceDigest` truncated to the first 8 hex chars so the L1 ring
 * stays compact when lease-aware tool calls run at high rate.
 *
 * Tail-only Optional parameter on `l1PushToolCallStarted` so existing
 * 4-arg positional callers (`tests/unit/l1-capture.test.ts:163`,
 * `tests/unit/l1-capture-panic-fuzz.test.ts:122,128`) keep compiling
 * unchanged (Round 1 P1-1, sub-plan §2.3).
 */
export interface NativeLeaseTokenSummary {
  entityId: string
  viewId: string
  targetGeneration: string
  evidenceDigestPrefix8: string
}

// ── ADR-015 Phase 3: VBA Extensibility bridge ────────────────────────────────
//
// Mirror types for the napi-rs binding in `src/vba_bridge.rs`. Session
// lifecycle uses integer handle IDs; the TS layer in Phase 4 will wrap
// these into the single `excel` MCP tool action dispatcher.

/** Read-only HKCU / HKLM `AccessVBOM` registry inspection result.
 * Returned by `excelCheckAccessVbom`. Mirrors
 * `engine_vba_bridge::registry::AccessVbomStatus` with `scope` as a
 * String (napi cannot marshal `&'static str` for an object field). */
export interface NativeExcelAccessVbomStatus {
  /** Effective trust state. `true` when either HKCU is 1 or HKLM forces 1. */
  trusted: boolean
  /** `true` only when HKLM is set to 0 (group policy forces denial). */
  lockedByPolicy: boolean
  /** `"hklm-policy"` (HKLM dictates), `"hkcu"` (HKLM unset, HKCU is 1), or `"default"` (neither set). */
  scope: string
}
